In [0]:
import tensorflow as tf


In [2]:
a = tf.constant([2,5,12])
b = tf.constant([3,5,14])
c = tf.add(a,b)
print(c)

Tensor("Add:0", shape=(3,), dtype=int32)


In [3]:
with tf.Session() as sess:
  print (c.eval())
  #result = sess.run(c)
  #print (result)

[ 5 10 26]


**Creating a 4 dimensional tensor using stack method !  **

In [0]:
# 1 dimnsional tensor (3,)
x1 = tf.constant([2,3,5])

In [0]:
# 2 dimensional tensor (2,3)
x2 = tf.stack([x1 , x1])

In [0]:
# 3 dimensional tensor (4,2,3)
x3 = tf.stack([x2,x2,x2,x2])

In [0]:
# 4 dimensional tensor (2,4,2,3)
x4 = tf.stack([x3,x3])

**Slicing Tensors**

In [8]:
# slicing x2 tensor!

y = x2[:,1]

with tf.Session() as sess:
  print(x2.eval())
  print(" y is : " , y.eval())
  

[[2 3 5]
 [2 3 5]]
 y is :  [3 3]


**Slicing of second element of every row **

**In Tensor flow we can reshape the tensors too !**

In [9]:
# reshaping the (2,3) matrix into (3,2). Since tf.reshape row by row, first two element of first row will be taken and then 3rd element of 1st row and 1 element of
# second row will be taken and so on !!
y = tf.reshape(x2 , [3,2])
with tf.Session() as sess:
  print(y.eval())

[[2 3]
 [5 2]
 [3 5]]
