#### Numpy is used for all matrix related operations !!

#### Table of Content
###### 1. Numpy array slicing 
###### 2. Matrix of value 1
###### 3. Memory allocation 
###### 4. Forcing a copy without any indexing trick
###### 5. Matrix multiplication 

In [2]:
import numpy as np

===================================================================================================================================================================

##### Numpy array slicing !!

In [38]:
x = np.array([
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]
            ])

In [47]:
x[:: 2 , :  ] 

# Double dot implies every alternate row, and how alternate is given by the number. 
# So here if it's x[:: 3 , : ] , that will mean every third element to be printed !
# if it is x[1::2 , : ], it means every second element starting from index 1(or second row will be printed !!!)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

==================================================================================================================================================================

###### Matrix of value 1 and dimension (3,3)


In [4]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# Here all the rows of x and in column 0 , 1 , 2 and a duplicate 2 is being printed !
x[: , [0,1,2,2]]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

==================================================================================================================================================================

##### Memory allocation !!

In [8]:
x = np.arange(5)

In [9]:
x

array([0, 1, 2, 3, 4])

In [10]:
y = x[[0,1,2]]

In [11]:
# Here y is being alloted it's own memory !! If we change value of x, value of y remain unaffected ! It is a copy !
y

array([0, 1, 2])

In [12]:
z = x[:3]

In [23]:
# Here z isn't alloted it's own memory, Instead it is using the memory used by x. So if we change any value of x , value of z changes. 
# z is a view here as it is created using slicing method
z

array([0, 1, 2])

In [14]:
x[0] = 999

In [15]:
x

array([999,   1,   2,   3,   4])

In [16]:
y

array([0, 1, 2])

In [17]:
z

array([999,   1,   2])

==================================================================================================================================================================

##### To explicitly force a copy without any indexing tricks, we can use .copy() method. !!!

In [18]:
t = x[:3].copy()

In [19]:
t

array([999,   1,   2])

In [20]:
x[0] = 0

In [21]:
x

array([0, 1, 2, 3, 4])

In [22]:
t

array([999,   1,   2])

===================================================================================================================================================================

##### Matrix multiplication !

In [24]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=np.array([[1],[0],[0]])

In [25]:
A.dot(x)

array([[1],
       [4],
       [7]])

In [26]:
np.dot(A,x) # It's same as A.dot(x)

array([[1],
       [4],
       [7]])

In [29]:
np.dot(x.T,A) # [ a*b and b*a is not same in matrix multiplication ! ]  (They may not even be multiplicable ! )

array([[1, 2, 3]])

In [30]:
A = np.ones((3,3))
x = np.ones((3,1))
# here A and x are not matrix and hence if we do multiply it will do scalar multiplication. 

In [34]:
A*x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# But if we do make it into matrix and multiply, it will do matrix multiplication!
np.matrix(A) * x

matrix([[3.],
        [3.],
        [3.]])

In [36]:
# another way is dot product !
A.dot(x)

array([[3.],
       [3.],
       [3.]])

In [37]:
# inner dot product !
np.dot(A,x)

array([[3.],
       [3.],
       [3.]])

==================================================================================================================================================================